### ISSUE TITLE
Nou ka jobé anlè.../On travail sur ..../We working on ....

### ISSUE THREAD

**Issue by NatsuGwada** [NatsuGwada/Projet_Git_Feat_C#23]
## Description
Ali a quitté le groupe

## Étapes de reproduction
1. Demande au collaborateur la raison de sa décision et lui demander confirmation oral
2. Accepter la décision du collaborateur
3. Supprimé collaborateur du repository

## Résultats attendus
Remove Ali

## Résultats réels
Ali Remove from de Repository

**Comment by gordibus** [comment]
Verification auprès d'Ali fait. 
Il n'aime pas travailler en groupe et il avait réalisé son travail donc il s'est permis de ne plus nous répondre et de quitter le groupe.
De plus étant donné qu'il n'a pas eu l'opportunité de signer avec une entreprise il ne pourra plus assister au cours d'avril.
