### ISSUE TITLE
Faire des templates

### ISSUE THREAD

**Issue by NatsuGwada** [NatsuGwada/Projet_Git_Feat_C#25]
**Votre demande de fonctionnalité est-elle liée à un problème ? Non
Besoin de créer des templates pour projet Git 

**Décrivez les alternatives que vous avez envisagées**
Issue template, Mege template, Pull request template

**Comment by gordibus** [comment]
Ouverture d'un template.

**Comment by gordibus** [comment]
Début des investigations.

**Comment by NatsuGwada** [comment]
issue template fait
pull request template fait
merge template fait
