### ISSUE TITLE
Brute Force on C

### ISSUE THREAD

**Issue by gordibus** [NatsuGwada/Projet_Git_Feat_C#7]
How can I read bruteforce on C ? Like what librery I need to know ? What is your tips to help me ?

**Comment by Aliiiiii404** [comment]
First of all u need to learn how to read a file , like if u have wordlist.txt that contains all the passwords to test u need to print all the passwords and then do a simple program that stores a random password from the wordlist in a variable and try to compare it with the other passwords in the wordlist. i think thats a good start.

**Comment by gordibus** [comment]
inside the program I'm going to use pointers to streamline the program. And then I need to use token for feedback to see how many failures there were before finding the right one.

**Comment by gordibus** [comment]
We need to make the program easier and use programming algorithms.

**Comment by NatsuGwada** [comment]
Passage soutenance réalisé. Dernière semaine de Mars
